version: '2.1'
orbs:
  python: circleci/python@2.1.1
  github: circleci/github-cli@1.0
aliases:
  - executor: &executor
      resource_class: small
      executor: python/default
  - test: &test
      <<: *executor
      steps:
        - checkout
        - python/install-packages:
            pkg-manager: poetry
        - run:
            command: |
              poetry run pytest tests/
            name: Run tests
jobs:
  lint:
    <<: *executor
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry
      - run:
          command: |
            poetry run isort --check --diff --color .
          name: Check imports sorted
      - run:
          command: |
            poetry run flake8
          name: Check the code style (Flake8)
      - run:
          command: |
            poetry run black --check --diff --color .
          name: Check the code style (Black)
  type:
    <<: *executor
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry
      - run:
          command: |
            poetry run mypy -p asyncio_multilock
          name: Type check the code
  py37:
    <<: *test
    docker:
      - image: cimg/python:3.7
  py38:
    <<: *test
    docker:
      - image: cimg/python:3.8
  py39:
    <<: *test
    docker:
      - image: cimg/python:3.9
  py310:
    <<: *test
    docker:
      - image: cimg/python:3.10
  py311:
    <<: *test
    docker:
      - image: cimg/python:3.11
  build:
    <<: *executor
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry
      - run:
          command: |
            poetry build
          name: Build package
      - persist_to_workspace:
          root: .
          paths:
            - dist
  release-pypi:
    <<: *executor
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          command: |
            poetry publish
          name: Publish package
workflows:
  main:
    jobs:
      - lint
      - type
      - py37
      - py38
      - py39
      - py310
      - py311
      - build:
          requires:
            - lint
            - type
            - py37
            - py38
            - py39
            - py310
            - py311
      - github/release:
          requires:
            - build
          tag: $CIRCLE_TAG
          title: $CIRCLE_TAG
          context:
            - GITHUB_CREDS
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^\d+\.\d+\.\d+$/
      - release-pypi:
          requires:
            - build
          context:
            - PYPI_CREDS
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^\d+\.\d+\.\d+$/
