version: '2.1'
orbs:
  python: circleci/python@2.1.1
  gh: circleci/github-cli@1.0
aliases:
  - executor: &executor
      resource_class: small
      executor: python/default
  - build: &build
      <<: *executor
      steps:
        - checkout
        - python/install-packages:
            pkg-manager: poetry
        - run:
            command: |
              poetry run pytest tests/
            name: Run tests
jobs:
  lint:
    <<: *executor
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry
      - run:
          command: |
            poetry run black --check --diff --color .
          name: Check the code style
  type:
    <<: *executor
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry
      - run:
          command: |
            poetry run mypy -p asyncio_multilock
          name: Type check the code
  py37:
    <<: *build
    docker:
      - image: cimg/python:3.7
  py38:
    <<: *build
    docker:
      - image: cimg/python:3.8
  py39:
    <<: *build
    docker:
      - image: cimg/python:3.9
  py310:
    <<: *build
    docker:
      - image: cimg/python:3.10
  py311:
    <<: *build
    docker:
      - image: cimg/python:3.11
workflows:
  main:
    jobs:
      - lint
      - type
      - py37
      - py38
      - py39
      - py310
      - py311
      - gh/release:
          requires:
            - lint
            - type
            - py37
            - py38
            - py39
            - py310
            - py311
          tag: v0.1.0
          title: v0.1.0
          context:
            - GITHUB_CREDS
          filters:
            tags:
              only:
                - v0.1.0
