name: Test publish

on: push

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment:
      name: test-pypi
      url: https://test.pypi.org/project/asyncio-multilock

    permissions:
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip toml
          pip install build

      - name: Add build number to package version
        shell: python
        run: |
          import toml
          
          with open("pyproject.toml", "r") as f:
            data = toml.load(f)
          
          data["project"]["version"] = f'{data["project"]["version"]}.dev${{ github.run_id }}'
          
          with open("pyproject.toml", "w") as f:
            toml.dump(data, f)

      - name: Build package
        run: python -m build

      - name: Publish package
        uses: pypa/gh-action-pypi-publish@v1.9.0
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}
          repository-url: https://test.pypi.org/legacy/
          skip-existing: true
